// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace BATTLENET_DESIGN.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("BATTLENET_DESIGN.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap apple_icon_57x57
        {
            get
            {
                var obj = ResourceManager.GetObject("apple_icon_57x57", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap CaptSSure_removebg_preview
        {
            get
            {
                var obj = ResourceManager.GetObject("CaptSSure_removebg_preview", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_apple_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_apple_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_faceboo2k_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_faceboo2k_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_facebook_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_facebook_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_facebook3_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_facebook3_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_facebook4_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_facebook4_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_google_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_google_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_hide_15
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_hide_15", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_hide_15__1_
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_hide_15__1_", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_nintendo_switch_logo_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_nintendo_switch_logo_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_playstation_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_playstation_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_playstation2_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_playstation2_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_steam_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_steam_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_xbox_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_xbox_50", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icons8_xbox2_50
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_xbox2_50", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}